In [1]:
import pandas as pd
data = pd.read_csv("data_folder/tweet_dataset.csv")
tweet_list = []
label_list = []
for each in list(data.iloc[:,2]):
    tweet_list.append(each.split())
for each in list(data.iloc[:,1]):
    label_list.append(each.split())
dataset_len = len(tweet_list)
train_tweet_list = tweet_list[:dataset_len*6//10]
test_tweet_list = tweet_list[dataset_len*6//10:]
train_label_list = label_list[:dataset_len*6//10]
test_label_list = label_list[dataset_len*6//10:]


# Classification using SVM

In [4]:
'''
Self Trained word vector of 100 length
'''
from gensim.models import Word2Vec
model = Word2Vec.load('model100')
vocab = model.wv.vocab

In [5]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
import numpy as np
X = []
for each in train_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = SVC(kernel='linear')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.85144999 0.51602024 0.41426783]
0.7665995975855131


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(['tweet_dataset.csv'],stop_words=None,analyzer='word')

vectorizer1 = TfidfVectorizer(['tweet_dataset.csv'],stop_words=None,analyzer='char')
vec = vectorizer.fit_transform(data.iloc[:,2])
vec1 = vectorizer1.fit_transform(data.iloc[:,2])
v = dict(zip(vectorizer.get_feature_names(),vectorizer.idf_))
v1 = dict(zip(vectorizer1.get_feature_names(),vectorizer1.idf_))



In [7]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if len(i)==1:
            t = t + model[i] * v1[i.lower()]
        else:
            t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = SVC(kernel='linear')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = colum

[0.85504514 0.54651163 0.438072  ]
0.7734096889026466


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [8]:
'''
Self Trained word vector of 200 length
'''
model = Word2Vec.load('model200')
vocab = model.wv.vocab

In [9]:
X = []
for each in train_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = SVC(kernel='linear')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.8497685  0.50973751 0.40125786]
0.7635041015322706


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [10]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if len(i)==1:
            t = t + model[i] * v1[i.lower()]
        else:
            t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = SVC(kernel='linear')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = colum

[0.85518746 0.55206612 0.43312883]
0.7735644637053087


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [11]:
'''
Self Trained word vector of 300 length
'''
model = Word2Vec.load('model300')
vocab = model.wv.vocab

In [12]:
X = []
for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = SVC(kernel='linear')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.85017696 0.49784668 0.40402769]
0.7636588763349327


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [13]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if len(i)==1:
            t = t + model[i] * v1[i.lower()]
        else:
            t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = SVC(kernel='linear')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = colum

[0.85425141 0.54439834 0.43467643]
0.7721714904813496


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [14]:
from gensim.models import KeyedVectors
model = KeyedVectors.load_word2vec_format("GoogleNews-vectors-negative300.bin",binary=True)

In [15]:
X = []
for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in model.wv.vocab:
            t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in model.wv.vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = SVC(kernel='linear')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.86159601 0.66806137 0.53433476]
0.7929113140380746


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [16]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = SVC(kernel='linear')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.85026794 0.64524949 0.52008239]
0.7774338337718619


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [17]:
model = KeyedVectors.load_word2vec_format("glove.50d.txt",binary=False)

In [18]:
X = []
for each in train_tweet_list:
    t = np.zeros(50)
    for i in each[1:]:
        if i in model.wv.vocab:
            t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(50)
    for i in each[1:]:
        if i in model.wv.vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = SVC(kernel='linear')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.83117136 0.34437086 0.32382134]
0.7280606717226435


array(['none', 'none', 'none', ..., 'sexism', 'none', 'none'], dtype='<U6')

In [19]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(50)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(50)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = SVC(kernel='linear')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.81940144 0.30409357 0.        ]
0.7000464324407987


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array(['none', 'none', 'none', ..., 'none', 'none', 'none'], dtype='<U6')

In [20]:
model = KeyedVectors.load_word2vec_format("glove.100d.txt",binary=False)

In [21]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import numpy as np
X = []
for each in train_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in model.wv.vocab:
            t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in model.wv.vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = SVC(kernel='linear')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.83945687 0.42307692 0.43019296]
0.7467884228447609


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [22]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = SVC(kernel='linear')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.82930677 0.40666082 0.32439024]
0.7279058969199814


array(['none', 'none', 'none', ..., 'sexism', 'none', 'none'], dtype='<U6')

In [23]:
model = KeyedVectors.load_word2vec_format("glove.200d.txt",binary=False)

In [24]:
X = []
for each in train_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in model.wv.vocab:
            t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in model.wv.vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = SVC(kernel='linear')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.84358275 0.46783626 0.46432492]
0.7553010369911778


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [25]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = SVC(kernel='linear')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.8341079  0.46217105 0.42367257]
0.7416808543569107


array(['none', 'none', 'none', ..., 'sexism', 'none', 'none'], dtype='<U6')

In [26]:
model = KeyedVectors.load_word2vec_format("glove.300d.txt",binary=False)

In [27]:
X = []
for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in model.wv.vocab:
            t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in model.wv.vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = SVC(kernel='linear')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.84771987 0.48867314 0.50053706]
0.7633493267296084


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [28]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = SVC(kernel='linear')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.84037223 0.4743083  0.48029819]
0.7522055409379353


array(['none', 'none', 'none', ..., 'sexism', 'none', 'none'], dtype='<U6')