In [1]:
import pandas as pd
data = pd.read_csv("data_folder/tweet_dataset.csv")
tweet_list = []
label_list = []
for each in list(data.iloc[:,2]):
    tweet_list.append(each.split())
for each in list(data.iloc[:,1]):
    label_list.append(each.split())
dataset_len = len(tweet_list)
train_tweet_list = tweet_list[:dataset_len*6//10]
test_tweet_list = tweet_list[dataset_len*6//10:]
train_label_list = label_list[:dataset_len*6//10]
test_label_list = label_list[dataset_len*6//10:]


# Classification using KNN

In [2]:
'''
Self Trained word vector of 100 length
'''
from gensim.models import Word2Vec
model = Word2Vec.load('model100')
vocab = model.wv.vocab

In [3]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
import numpy as np
X = []

for each in train_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  # Remove the CWD from sys.path while we load stuff.
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


[0.82407888 0.51076923 0.44287871]
0.7339421142238044


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(['tweet_dataset.csv'],stop_words=None,analyzer='word')

vectorizer1 = TfidfVectorizer(['tweet_dataset.csv'],stop_words=None,analyzer='char')
vec = vectorizer.fit_transform(data.iloc[:,2])
vec1 = vectorizer1.fit_transform(data.iloc[:,2])
v = dict(zip(vectorizer.get_feature_names(),vectorizer.idf_))
v1 = dict(zip(vectorizer1.get_feature_names(),vectorizer1.idf_))

In [5]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if len(i)==1:
            t = t + model[i] * v1[i.lower()]
        else:
            t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


[0.83011862 0.54504164 0.43546695]
0.7427642779755456


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [6]:
'''
Self trained word vector of 200 length
'''

model = Word2Vec.load('model200')
vocab = model.wv.vocab

In [7]:
X = []

for each in train_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  from ipykernel import kernelapp as app
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


[0.82494552 0.52647736 0.43794147]
0.7354898622504257


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [8]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if len(i)==1:
            t = t + model[i] * v1[i.lower()]
        else:
            t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


[0.82801236 0.52255054 0.43302181]
0.7387401331063302


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [9]:
'''
Self trained word vector of 300 length
'''

model = Word2Vec.load('model300')
vocab = model.wv.vocab

In [10]:
X = []

for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  from ipykernel import kernelapp as app
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


[0.82194895 0.51086957 0.42309658]
0.7305370685652376


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [11]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if len(i)==1:
            t = t + model[i] * v1[i.lower()]
        else:
            t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


[0.83141447 0.52655889 0.44010554]
0.7433833771861941


array(['none', 'none', 'none', ..., 'sexism', 'sexism', 'none'],
      dtype='<U6')

In [12]:
from gensim.models import KeyedVectors
model = KeyedVectors.load_word2vec_format("GoogleNews-vectors-negative300.bin",binary=True)
vocab = model.wv.vocab

MemoryError: 

In [ ]:
X = []

for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

In [ ]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

In [ ]:
'''
Model with word vector dimension 300
'''
model = KeyedVectors.load_word2vec_format("glove.300d.txt",binary=False)
vocab = model.wv.vocab

In [ ]:
X = []

for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

In [ ]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(300)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
print(acc)
pred

In [ ]:
'''
Model with word vector dimension 200
'''
model = KeyedVectors.load_word2vec_format("glove.200d.txt",binary=False)
vocab = model.wv.vocab

In [ ]:
X = []

for each in train_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

In [ ]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(200)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

In [ ]:
'''
Model with word vector dimension 100
'''
model = KeyedVectors.load_word2vec_format("glove.100d.txt",binary=False)
vocab = model.wv.vocab

In [ ]:
X = []

for each in train_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

In [ ]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(100)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

In [ ]:
'''
Model with word vector dimension 50
'''
model = KeyedVectors.load_word2vec_format("glove.50d.txt",binary=False)
vocab = model.wv.vocab

In [ ]:
X = []

for each in train_tweet_list:
    t = np.zeros(50)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]
    t = t / len(each)
    X.append(t)
    
test_vector = []
for each in test_tweet_list:
    t = np.zeros(50)
    for i in each[1:]:
        if i in vocab:
            t = t + model[i]                    
    t = t / len(each)
    test_vector.append(t)
    
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X,train_label_list)
pred = clf.predict(test_vector)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred

In [ ]:
X_tf = []
for each in train_tweet_list:
    t = np.zeros(50)
    for i in each[1:]:
        if i in vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]
    t = t / len(each)
    X_tf.append(t)
'''
converting test tweet dataset to word vectors
'''
test_vector_tf = []
for each in test_tweet_list:
    t = np.zeros(50)
    for i in each[1:]:
        if i in model.wv.vocab:
            if len(i)==1:
                t = t + model[i] * v1[i.lower()]
            else:
                t = t + model[i] * v[i.lower()]      
    t = t / len(each)
    test_vector_tf.append(t)
clf = KNeighborsClassifier(algorithm='auto')
clf.fit(X_tf,train_label_list)
pred = clf.predict(test_vector_tf)
acc = accuracy_score(test_label_list,pred)
f1 = f1_score(test_label_list,pred,average=None)
print(f1)
print(acc)
pred